<MyLayout>
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height
        Label:
            text: "Head Motion"
            font_size:32

        GridLayout:
            cols:2

            Label:
                id: turn_right
                text: "Turn Right"
                font_size:20
            Checkbox:
                on_active: root.checkbox_click(self, self.active, "Right")
        Label:
            id: output
            text: ""